version: "3.8"

services:
  frontend:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ecommerce-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build:
      context: ./ecommerce-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./ecommerce-backend:/app
      - ./ecommerce-backend/instance:/app/instance
    environment:
      - FLASK_ENV=development
    stdin_open: true
    tty: true