name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm install  # Changed from npm ci to npm install
    
    - name: Run React tests
      run: npm test -- --watchAll=false
    
    - name: Run Cypress tests
      run: npm run cypress:run
    
    - name: Run API tests
      run: newman run api-tests/StoreCartTest.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to production
      run: |
        # Add your deployment commands here
        echo "Deploying to production"