name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    
    - name: Install dependencies
      run: |
        cd ecommerce-frontend
        npm ci || npm install
        if [ $? -ne 0 ]; then
          npm install
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package-lock.json
          git commit -m "Update package-lock.json" || echo "No changes to commit"
          git push
        fi

    - name: Install backend dependencies
      run: |
        cd ecommerce-backend
        pip install -r requirements.txt  # Assuming you have a requirements.txt file
    
    - name: Run React tests
      run: npm test -- --watchAll=false

    - name: Start backend server
      run: |
        cd ecommerce-backend
        python app.py &  # Adjust this to your Python script that starts the server
      env:
        CI: true
    
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        working-directory: ecommerce-frontend
        build: npm run build
        start: npm start
        wait-on: 'http://localhost:3000,http://localhost:5000'
        config-file: cypress.config.js
      env:
        CI: true

    - name: Upload Cypress screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: ecommerce-react-app/cypress/screenshots

    - name: Upload Cypress videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: ecommerce-react-app/cypress/videos

    - name: Install Newman
      run: npm install -g newman
    
    - name: Run API tests
      run: npx newman run api-tests/StoreCartTest.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to production
      run: |
        # Add your deployment commands here
        echo "Deploying to production"